spring:
  r2dbc:
    url: r2dbc:postgresql://db:5432/db?schema=db
    username: postgres
    password: postgres

server:
  port: 80

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /swagger-doc/v3/api-docs
  swagger-ui:
    path: /swagger-doc/swagger-ui.html

logging:
  level:
    org:
      springframework: INFO
