spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db?schema=db
    username: postgres
    password: postgres
    spring:
      jackson:
        property-naming-strategy: CASE_INSENSITIVE

server:
  port: 8080

logging:
  level:
    org:
      springframework: INFO
