name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Initialize
        run: terraform -chdir=contact-management-api/terraform init

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform -chdir=contact-management-api/terraform apply -auto-approve

      - name: Get EC2 IP
        id: ec2_ip
        run: echo "::set-output name=ip::$(terraform -chdir=contact-management-api/terraform output public_ip)"

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > deployer_key
          chmod 600 deployer_key
          scp -o StrictHostKeyChecking=no -i deployer_key docker-compose.yml ec2-user@${{ steps.ec2_ip.outputs.ip }}:/home/ec2-user/
          ssh -o StrictHostKeyChecking=no -i deployer_key ec2-user@${{ steps.ec2_ip.outputs.ip }} "sudo apt-get update && sudo apt-get install -y docker docker-compose && sudo systemctl start docker && sudo systemctl enable docker && sudo docker-compose up --build -d"